version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    networks:
      - project-network
    ports:
      - "2344:${DB_PORT}"

  app:
    build:
      context: .
    env_file:
      - project/backend/app/.env
    container_name: fastapi
    restart: always
    command: [ "project/backend/deploy/app.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - project-network

  s3:
    image: minio/minio
    container_name: myminio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - project-network

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add myminio http://${ENDPOINT_URL} ${ACCESS_KEY} ${SECRET_KEY};
      /usr/bin/mc mb myminio/${BUCKET};
      sleep 999;
      exit 0;
      "
    networks:
      - project-network

  redis:
    image: redis
    hostname: redis_app
    container_name: redis_app
    command: --port ${REDIS_PORT}
    ports:
      - "6378:${REDIS_PORT}"
    networks:
      - project-network
    volumes:
      - cache:/data

networks:
  project-network:
    driver: bridge

volumes:
  static:
  media:
  minio-storage:
  cache:
