"""Add refreshtoken

Revision ID: 4ccb45fa8be0
Revises: d26bab15a050
Create Date: 2023-10-07 20:25:02.946783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb45fa8be0'
down_revision = 'd26bab15a050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('refresh_token',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('refresh_token', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('uuid')
                    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
