name: flake8

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install poetry
        poetry install

    - name: Test with flake8
      run: |
        poetry run flake8